# Site settings
name: BuildForSTL
title: BuildForSTL - St Louis' National Day of Civic Hacking
email: b@buildforstl.org
description: New github hosted website for Build for STL
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://buildforstl.org

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: /
twitter_username: build4stl
github_username:  blordcastillo
# highlighter: rouge
# Build settings
markdown: kramdown
permalink: /:title/
version: v1.0.0
paginate: 5

# Exclude these files from your production _site
exclude:
    - Gemfile
    - README.md
